### PR TITLE
SWIK-840 media-file-upload-dialog

### PR DESCRIPTION
**Pull request by rmeissn**
NOT FINISHED YET

I had to add a new parameter to the route. I might need to change the stored license information as well.

### CODE REVIEW

**Comment by rmeissn** [comment]
I've added a new route as a v2 route and deprecated the old one. I added additional query params according to my chat with @kadevgraaf and to SWIK-840 and had to delete one (reason for the v2 route).

New route: 
route

I haven't yet tested these changes via real usage. Does this route look okay to you or is something missing/mistakable, @kadevgraaf ?

The changes of the media model require to write a little script that will convert the MongoDB contents of the media namespace. This is still a TODO.

**Review by kadevgraaf — APPROVED** [review]
This looks good. Thanks!

**Comment by kadevgraaf** [comment]
FYI: I currently getting response
400 - "{\"statusCode\":400,\"error\":\"Bad Request\",\"message\":\"\\\"altText\\\" is not allowed\",\"validation\":{\"source\":\"query\",\"keys\":[\"altText\"]}}"

when sending the following
 
--
g0 | {…}
resource | media.create
operation | create
params | {…}
type | image/png
license | CC0
title | Screen Shot 2017-10-25 at 17.48.12.png
filesize | 207416
filename | Screen Shot 2017-10-25 at 17.48.12.png
bytes | data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABgoAAANWCAYAAAAvI9fvAAAMFWlDQ1BJQ0MgUHJvZmlsZQAASImVVwdUk8kWnr+kEBJaIAJSQu9IkS4QOkiVDjZCEiCUCAlBxY4sKrgWVCwoKroCYlsLIIsNUSwsgr0vqKisrIsFGypvUkCfr513z5l/vty59853J3fmzACgbMfOzc1GVQDIEeQLo4N8mYlJyUxSLyABDNAAE5ixOaJcn6ioMABltP9neXcTIJL+mo0k1r+O/1dR5fJEHACQKIhTuSJODsRHAcA1ObnCfAAIHVBvNDs/V4IHIVYXQoIAEHEJTpdhTQlOlWFrqU1stB/ELADIVDZbmA6AkoQ3s4CTDuMoSTjaCbh8AcRbIfbiZLC5EN+H2DonZxbEymSIzVO/i5P+TzFTx2Ky2eljWJaLVMj+fFFuNnvu/7kc/1tyssWjcxjCRs0QBkdLcobrVps1K1SCqRC3CFIjIiFWg/…Mud4nVSgAIUoAAFKEABClCAAhSgAAUoQAEK2CGg8Udr2fAEOBInXzqciQI79OO0TyYKZu/GRZINmjA4eeYszrVcwtqqSrizs5GcnIzA0BCWFPhw7foNeCR50NbRgfBwGG63G909PSZYX1a0zBRZbu/sRHhkBOUlxSbBcPnqNZ1VhJVPrED/4B2cu/APsjKdWF5cDP+//WhrbzcDLZa6EF7v/6uREC+Fl2fvTvJMFKAABShAAQpQgAIUoAAFKEABClCAAhSIfwEmCuL/Hs7YCJgomDHKh3YUnShoPH0GJ842oay4CMtLS9DffwedXV148fln8ePRn7G2shKnmpplLTGPSQTc7O42SxTp++BQED1S70H7K1q6BAODAVxva5c6CgN4rmY98j15+LW+AcOhEJ5aVYWbPb1ovdYKl8uFPElAPFP99EOvNfoAJgqiNfg3BShAAQpQgAIUoAAFKEABClCAAhSgAAXmh8B/fzWQX7r0lIQAAAAASUVORK5CYII=
userid | 2
jwt | eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjIsInVzZXJuYW1lIjoia2FkZXZncmFhZiIsImVtYWlsIjoia2EuZGUuZ3JhYWZAdnUubmwiLCJpc1Jldmlld2VyIjpmYWxzZSwiaWF0IjoxNTA4ODU1ODM3fQ.8FELUCKpkWnBZjrnD3fSivcPTAwUgtAo94xgypZKiETxQWOhkOz_br1qQYoh0CuKD-z7KXEagl64ADM4_Tic2Q
body | {…}
timeout | 20000

from branch SWIK840 from platform

So even though I do not send an alttext (I think) I get an error returned from file-service

**Comment by rmeissn** [comment]
I guess you're still using route v1, as this is what is implemented in https://github.com/slidewiki/slidewiki-platform/compare/SWIK-840-media-file-upload-dialog#diff-e57c629a3f6f5265bef03d64c19454f7R17

Both routes (v1 and v2) support altTexts as query parameters. I don't see why Hapi shoud complain with this message. Will test for.

**Comment by rmeissn** [comment]
I've tested this PR via Curl: It's for both routes possible to issue a request without the "altText" query param and also with it. 

EDIT: I've updated branch SWIK-840 at platform to match the new route (but no other improvements/fixes)

**Comment by kadevgraaf** [comment]
My mistake - I did not test V2 againts this branch/PR. This would be perfect to merge. Many thanks for the nice new route :+1:

**Comment by rmeissn** [comment]
Added a migration script to convert the media database to the new format. Works very well for the experimental database.
Could you please verify the script, @TBoonX ?

**Pull request merged**
