### PR TITLE
Added route to search for pictures of a user

### PR DESCRIPTION
**Pull request by rmeissn**
Needed for https://slidewiki.atlassian.net/browse/SWIK-1063 .
I still might need to modify the response fields, depending on the used frontend plugin.

Btw.: Should this be a secured route (Only requestible with valid JWT)?

### CODE REVIEW

**Comment by TBoonX** [comment]
Because this just adds stuff which is not used atm, I only could approve it.
If JWT is needed should be answered and eventually implemented before merging this into master. I think we do not need it there because all pictures are public.

**Comment by rmeissn** [comment]
Well, I think this functionality will be used by a photo gallery within this sprint - at least that's my plan.

**Comment by rmeissn** [comment]
@rmeissn Revise the route in order to make it more similar to https://github.com/slidewiki/deck-service/pull/86

**Comment by rmeissn** [comment]
As there are no objections for 25 days, I will merge this ticket now.

**Pull request merged**
